create database inventory;

create table users(
    id_user SERIAL,
    name varchar(60),
    document int,
    position varchar(70),
    management varchar(40) ,   
    departament varchar(50), 
    sede varchar(50),
    society varchar(50),
    ceco varchar(10),
    extension varchar(4),
    corporateMovil varchar(10),
    personalMovil varchar(10),
    windowsUser varchar(15),
    emailUser varchar(70),
    sapUser varchar(15),
    internetPermision varchar(20),
    latitude varchar(9),
    longitude varchar(9),
    address varchar(50),
    city varchar(20),
    route varchar(30),
    stop varchar(100),
    typeUser varchar(12),
    statusUser varchar(15),
    dateTimeCreation timestamp default CURRENT_TIMESTAMP,
    dateTimeElimination timestamp ,
    motiveDelete varchar(50)
);

insert into public."users" values (
    name = 'David Suarez Losada',
    document = 1075258636,
    position = 'Auxiliar Administrativo',
    management = ' Administración' ,   
    departament = 'Administración y Finanzas', 
    sede = 'Oficina Central',
    society = 'Central Cervecera',
    ceco = '',
    extension = '2645',
    corporateMovil = '',
    personalMovil = '3192146220',
    windowsUser = 'dsuarezl',
    emailUser = 'dsuarezl@centralcervecera.com',
    sapUser = 'CCDSUAREZ',
    internetPermision = 'Web full',
    latitude = '',
    longitude = '',
    address = 'Cll 126 # 47 - 52',
    city = 'Bogotá',
    route = 'Autonorte',
    stop = 'Cll 127',
    typeUser = 'Office 365',
    statusUser = 'Activo',
    motiveDelete =''
);

insert into public."users" (
    name,
    document,
    position,
    management,   
    departament, 
    sede,
    society,
    ceco,
    extension,
    corporateMovil,
    personalMovil,
    windowsUser,
    emailUser,
    sapUser,
    internetPermision,
    latitude,
    longitude,
    address,
    city,
    route,
    stop,
    typeUser,
    statusUser ,
    motiveDelete) 
    
    values (
    'David Suarez Losada',
    1075258636,
    'Auxiliar Administrativo',
    ' Administración' ,   
    'Administración y Finanzas', 
    'Oficina Central',
    'Central Cervecera',
    '',
    '2645',
    '',
    '3192146220',
    'dsuarezl',
    'dsuarezl@centralcervecera.com',
    'CCDSUAREZ',
    'Web full',
    '',
    '',
    'Cll 126 # 47 - 52',
    'Bogotá',
    'Autonorte',
    'Cll 127',
    'Office 365',
    'Activo',
    ''
);